// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"database/sql"
	"time"
)

type Business struct {
	BusinessID     int64          `json:"business_id"`
	Name           string         `json:"name"`
	City           string         `json:"city"`
	Address        string         `json:"address"`
	Latitude       string         `json:"latitude"`
	Longitude      string         `json:"longitude"`
	UbicationPhoto sql.NullString `json:"ubication_photo"`
	CreatedAt      time.Time      `json:"created_at"`
}

// primary key 🔑 is composed by business_id and user_id
type BusinessMember struct {
	BusinessID int64 `json:"business_id"`
	UserID     int64 `json:"user_id"`
	// posible positions for the employee, dueño, administrador, empleado
	BusinessPosition string    `json:"business_position"`
	CreatedAt        time.Time `json:"created_at"`
}

type Session struct {
	UserIDSession int64     `json:"user_id_session"`
	Valid         bool      `json:"valid"`
	UserAgent     string    `json:"user_agent"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

// primary key is composed by user_id and social_id, both of those properties are unique
type User struct {
	UserID int64 `json:"user_id"`
	// this field is for the unique id provided by google, or facebook, or tik tok etc etc.. to identify a user
	SocialID     string    `json:"social_id"`
	Username     string    `json:"username"`
	Email        string    `json:"email"`
	Picture      string    `json:"picture"`
	Provider     string    `json:"provider"`
	RegisteredAt time.Time `json:"registered_at"`
}
