// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"context"
)

type Querier interface {
	AddBusinessMember(ctx context.Context, arg AddBusinessMemberParams) (BusinessMember, error)
	CreateBusiness(ctx context.Context, arg CreateBusinessParams) (Business, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GenerateSession(ctx context.Context, arg GenerateSessionParams) (Session, error)
	GetSession(ctx context.Context, userIDSession int64) (Session, error)
	GetUserById(ctx context.Context, userID int64) (User, error)
	GetUserBySocialId(ctx context.Context, socialID string) (User, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
